version: "3.3"

services:
  client:
    image: ${IMAGE_REGISTRY_LOCATION}
    environment:
      - NODE_ENV=production
    networks:
      - proxy
      - mongo
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.srcPort=80
        - com.df.port=8080
        - com.df.httpsOnly=true
        - com.df.srcHttpsPort=443
        - com.df.httpsPort=8080

networks:
  proxy:
    external: true
  mongo:
    external: true